spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://USER-SERVICE
              predicates:
                - Path=/api/v1/user/**
            - id: activity-service
              uri: http://ACTIVITY-SERVICE
              predicates:
                  - Path=/api/v1/activity/**
            - id: ai-service
              uri: http://AI-SERVICE
              predicates:
                - Path=/api/v1/recommendation/**
logging:
  level:
    org.springframework.cloud.gateway: TRACE
server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/